//! Product-agnostic media-primitive schema — buffa-generated message types.
//!
//! Generated code lives in `src/generated/` and is regenerated by
//! `cargo run -p xtask -- gen`. Do not edit generated files by hand.

#![cfg_attr(docsrs, feature(doc_cfg))]

mod generated {
    include!("generated/mod.rs");
}

// Flatten the product-neutral `media.v1` package to the crate root so
// consumers write `mediaschema::Detection`, not `mediaschema::media::v1::…`.
pub use generated::media::v1::*;
