//! Product-agnostic media-primitive schema — buffa-generated message types.
//!
//! Generated code lives in `src/generated/` and is regenerated by
//! `cargo run -p xtask -- gen`. Do not edit generated files by hand.

#![cfg_attr(docsrs, feature(doc_cfg))]

#[allow(warnings, clippy::all)]
mod generated {
    include!("generated/mod.rs");
}

// Flatten the product-neutral `media.v1` package to the crate root so
// consumers write `mediaschema::Detection`. Named (not glob) so buffa
// internals (`__buffa`, `__*_JSON_ANY`) stay out of the public surface.
pub use generated::media::v1::{
    Aesthetics, AudioFormat, BoundingBox, CodecId, Detection, Dimensions, DocumentSegment,
    FeaturePrint, HorizonInfo, MediaKind, Point2D, TimedDetection, VideoFormat,
};
/// Oneof variant for [`MediaKind`]: `Kind::Video(…)` or `Kind::Audio(…)`.
pub use generated::media::v1::media_kind::Kind as MediaKindKind;
