//! Product-agnostic media-primitive schema — buffa-generated message types.
//!
//! Generated code lives in `src/generated/` and is regenerated by
//! `cargo run -p xtask -- gen`. Do not edit generated files by hand.
//!
//! ## Feature surface (three tiers)
//!
//! - `--no-default-features` ⇒ **no-std + no-alloc**. Only the
//!   stack-only domain types: `Uuid7` / `Uuid7Error`, `FileChecksum`,
//!   `Rgba`, `ErrorCode` / `UnknownErrorCode`, `LocationError`, plus
//!   every unit-variant enum and `bitflags!` companion. The
//!   buffa-generated wire layer is **not** compiled.
//! - `--no-default-features --features alloc` ⇒ **no-std + alloc**.
//!   Adds heap-using domain types: `Location` / `LocalLocation`,
//!   `ErrorInfo`, `Provenance`, `LocalizedText` (everything reaching
//!   `Vec` / `SmolStr`). Wire layer still not compiled.
//! - `--features std` (default) ⇒ **std**, implies `alloc`. Adds the
//!   buffa-generated wire layer (`mediaschema::Detection`, …) and the
//!   `jiff`-using aggregates (`Speaker`, `WatchedLocation`, `UserTag`,
//!   `SceneAnnotation`).

#![cfg_attr(not(feature = "std"), no_std)]
#![cfg_attr(docsrs, feature(doc_cfg))]

// Alias `alloc as std` on no-std + alloc builds so domain code can use
// `std::vec::Vec` / `std::string::String` uniformly across feature
// combos. When `feature = "std"` is on, the real `std` is in scope via
// the prelude (its `extern crate` is implicit).
#[cfg(all(not(feature = "std"), feature = "alloc"))]
#[allow(unused_extern_crates)]
extern crate alloc as std;

#[cfg(feature = "buffa")]
#[allow(unused_extern_crates)]
extern crate std;

// Wire layer (buffa-generated) is `std`-only. The codegen uses `Vec` /
// `String` (need alloc) AND the buffa runtime utilities pull in std
// path types — gating the whole module on `feature = "std"` is the
// simplest correct shape.
#[cfg(feature = "buffa")]
#[allow(warnings, clippy::all)]
mod generated {
  include!("generated/mod.rs");
}

/// Hand-written domain layer — the architectural hub. App logic programs
/// against `mediaschema::domain::*`; the buffa-generated wire types at the
/// crate root (re-exported from `generated::media::v1::*`, available with
/// `feature = "std"`) are the serialization edge. Domain ⇄ wire conversions
/// are added incrementally as each aggregate lands (with `domain → wire →
/// domain` round-trip property tests). See `schema/*.md` for the locked
/// specifications.
pub mod domain;

// Wire ⇄ domain conversion bridge. Requires `feature = "buffa"` (for
// the wire types themselves) AND a heap tier (`std` or `alloc`) because
// every domain type the bridge touches that has a wire counterpart
// (`Location`, `ErrorInfo`, `WatchedLocation`, `Media`, …) is itself
// `any(std, alloc)`-gated.
#[cfg(all(feature = "buffa", any(feature = "std", feature = "alloc")))]
#[cfg_attr(
  docsrs,
  doc(cfg(all(feature = "buffa", any(feature = "std", feature = "alloc"))))
)]
pub mod buffa;

/// `sqlx` row-mapping backend — Postgres / MySQL / SQLite. Off by default;
/// enable one (or more) of `sqlx-postgres` / `sqlx-mysql` / `sqlx-sqlite`.
#[cfg(any(
  feature = "sqlx-postgres",
  feature = "sqlx-mysql",
  feature = "sqlx-sqlite"
))]
#[cfg_attr(
  docsrs,
  doc(cfg(any(
    feature = "sqlx-postgres",
    feature = "sqlx-mysql",
    feature = "sqlx-sqlite"
  )))
)]
pub mod sqlx;

/// Optional MongoDB backend — `bson::Document` ↔ domain aggregates plus
/// per-collection [`::mongodb::IndexModel`](mongodb::IndexModel)
/// constructors. Off by default; enable with `--features mongodb`.
/// Inside the module the external `::mongodb` crate is referenced via
/// its absolute path so the `crate::mongodb` module name does not
/// shadow it.
#[cfg(feature = "mongodb")]
#[cfg_attr(docsrs, doc(cfg(feature = "mongodb")))]
pub mod mongodb;

// Flatten the product-neutral `media.v1` package to the crate root so
// consumers write `mediaschema::Detection`. Named (not glob) so buffa
// internals (`__buffa`, `__*_JSON_ANY`) stay out of the public surface.
// SP2 database-domain types (same media.v1 package since mono-consolidation).
// SP3 network-domain types (same media.v1 package since mono-consolidation).
/// Oneof variant for [`Event`]: the `kind` discriminant arm.
#[cfg(feature = "buffa")]
pub use generated::media::v1::event::Kind as EventKind;
/// Oneof variant for [`Location`]: `Kind::Local(…)`.
#[cfg(feature = "buffa")]
pub use generated::media::v1::location::Kind as LocationKind;
/// Oneof variant for [`LocationTarget`]: `Kind::Local(…)`.
#[cfg(feature = "buffa")]
pub use generated::media::v1::location_target::Kind as LocationTargetKind;
/// Oneof variant for [`MediaKind`]: `Kind::Video(…)` or `Kind::Audio(…)`.
#[cfg(feature = "buffa")]
pub use generated::media::v1::media_kind::Kind as MediaKindKind;
/// Oneof variant for [`Request`]: the `kind` discriminant arm.
#[cfg(feature = "buffa")]
pub use generated::media::v1::request::Kind as RequestKind;
/// Oneof variant for [`Response`]: the `kind` discriminant arm.
#[cfg(feature = "buffa")]
pub use generated::media::v1::response::Kind as ResponseKind;
/// Oneof variant for [`SubtitleTrackOrigin`]: `Source::SourceAudioTrackId(…)` or `Source::SourceSubtitleTrackId(…)`.
#[cfg(feature = "buffa")]
pub use generated::media::v1::subtitle_track_origin::Source as SubtitleTrackOriginSource;
#[cfg(feature = "buffa")]
pub use generated::media::v1::{
  ActionDetection, Aesthetics, AnimalAnalysis, AppPathBuf, Audio, AudioAnalysis,
  AudioChannelLayout, AudioChannelOrderKind, AudioChannelSpec, AudioClipKind, AudioCodec,
  AudioContainerFormat, AudioCoverArt, AudioEvent, AudioFileRecord, AudioFormat, AudioMeta,
  AudioPrefilterClass, AudioSampleFormat, AudioSegment, AudioStreamMeta, AudioSummary, AudioTrack,
  AudioTrackMeta, AudioTrackRole, AudioTranscriptSegment, BarcodeDetection, BodyPose3DDetection,
  BodyPose3DHeightEstimation, BodyPose3DJoint, BodyPoseDetection, BodyPoseJoint, BoundingBox,
  BrowseItem, BrowseRequest, BrowseResponse, Ced, CedDetection, ChannelLayoutKind, Chromaprint,
  Clap, ClassificationDetection, CodecId, ColorDetection, DbMediaKind, Detection, Dimensions,
  DocumentSegment, Ebur128, EjectVolumeRequest, EjectVolumeResponse, EmotionDetection, ErrorInfo,
  Event, FaceDetection, FaceLandmarkPoint, FaceLandmarkRegion, FaceLandmarksDetection, FailedFile,
  FailedFilesResponse, FeaturePrint, FileChecksum, FolderUpdatedEvent, GetDaemonInfoRequest,
  GetDaemonInfoResponse, GetFileIndexingStatsRequest, GetFileIndexingStatsResponse,
  GetIndexedFileRequest, GetIndexedFileResponse, GetLocationStatsRequest, GetLocationStatsResponse,
  GetModelStatusRequest, GetModelStatusResponse, HandChirality, HandPoseDetection,
  HeartbeatRequest, HeartbeatResponse, HorizonInfo, HumanAnalysis, Id, IndexLocationRequest,
  IndexLocationResponse, IndexingFile, IndexingProgressResponse, Keyframe, Language,
  LightingDetection, ListLocationsRequest, ListLocationsResponse, Local, LocalizedText, Location,
  LocationTarget, Media, MediaFile, MediaKind, MediaMeta, ModelDownloadProgress,
  ModelDownloadProgressEvent, ModelDownloadProgressResponse, ModelInfo, MoodDetection,
  NetFailedFile, ObjectDetection, Pagination, Person, PersonConfidence,
  PersonInstanceMaskDetection, PersonSegmentationMask, Point2D, Provenance, RemoveLocationRequest,
  RemoveLocationResponse, Request, RequestEnvelope, Response, ResponseEnvelope, RetryFailedRequest,
  RetryFailedResponse, SaliencyRegion, Scene, SceneMeta, SceneVlmResult, SearchFilter, SearchHit,
  SearchRequest, SearchResponse, SoundSource, Sp2CodegenSmoke, Sp3CodegenSmoke, Speaker,
  SpeakerSegment, SubjectDetection, Subtitle, SubtitleCue, SubtitleMeta, SubtitleTrack,
  SubtitleTrackFormat, SubtitleTrackMeta, SubtitleTrackOrigin, SubtitleTrackRole, Tag,
  TagConfidence, TextDetection, Timecode, TimedDetection, TrackClassificationType, TrackRecord,
  TrackTag, TrackTime, TrackTimeSource, UpdateAnnotationRequest, UpdateAnnotationResponse, Video,
  VideoFormat, VideoMeta, VideoStreamMeta, VideoTrack, VideoTrackMeta, VoiceFingerprint, Volume,
  VolumeMeta, VolumeStateChangedEvent, WatchedLocation, Word,
};
